version: 0.2
phases:
  pre_build:
    commands:
      - pip install --upgrade awscli
      - dotnet restore AwsWebApp7/AwsWebApp7.csproj

  build:
    commands:
      - dotnet publish -c release -o ./build_output AwsWebApp7/AwsWebApp7.csproj
      
artifacts:
  files:
    - template.yml
    - AwsWebApp7/build_output/**/*
    - scripts/**/*
    - appspec.yml
